# Site settings
title: Open Speeches
email: hllbck7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a collection of all the congressional debate speeches for the RHS team to use for inspiration and learning. I highly encourage reusing as much as you can, but always remember that the strongest speeches are original, and by only using the ideas of others you limit yourself to the past while forfeiting an innovative future. 
baseurl: "/OpenSpeeches" 
url: "http://lbarberiscanoni.github.io/OpenSpeeches"

# Build settings
markdown: kramdown
gems: ['jekyll_video_tag'] 
github:
    repo: lbarberiscanoni/OpenSpeeches
    branch: master

